# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Faez Baharin
title: Flutter Developer / Web Designer
email: faezbaharin@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  faezbaharin
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: fvezbrn
linkedin_username: faezbaharin
# pinterest_username: jekyll
youtube_username: channel/UC5CTyS5EyXkm1YaDA2Q__xg
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/icon.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Faez Baharin. I'm fast learning person in information technology field and have enthusiasm into graphical design. I'm willing to learn new things, which can improve my skill while contributing benefits to the organization. I'm also able to work under minimal supervision in order to complete the task given.


  Currently I have most experience working with are: <mark>PHP</mark> <mark>HTML5</mark> <mark>Laravel</mark> <mark>Flutter</mark> <mark>Git</mark>
  <mark>MySQL</mark>

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience



# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
# footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
